version: '3'

services:
  web:
    build: .
    volumes:
      - .:/opt/code
      - ./data/media:/var/www/media
      - static:/var/www/static
    depends_on:
      - db
  db:
    image: mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: proj2004
    volumes:
      - ./data/db:/var/lib/mysql
  nginx:
    image: nginx
    ports:
      - ${PORT-8000}:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/media:/var/www/media
      - static:/var/www/static
    depends_on:
      - web

volumes:
  static:
