MODE: deploy
BASE_URL: http://127.0.0.1:8000
SECRET_KEY: '<secret key>'
ALLOWED_HOSTS:
  - '*'
DATABASES:
  default:
    ENGINE: django.db.backends.mysql
    HOST: db
    NAME: proj2004
    USER: root
    PASSWORD: 'password'
    OPTIONS:
      init_command: "SET sql_mode='STRICT_TRANS_TABLES'"
